- hosts: physical
  become_method: sudo
  become_user: root
  become: true

  vars:
    raid_name: raid

  tasks:
  - name: Download Ubuntu cloud image
    get_url:
      url: https://cloud-images.ubuntu.com/minimal/releases/focal/release/ubuntu-20.04-minimal-cloudimg-amd64.img
      dest: /mnt/pve/{{ raid_name }}/template/iso/ubuntu-20.04-minimal-cloudimg-amd64.img
      checksum: sha256:https://cloud-images.ubuntu.com/minimal/releases/focal/release/SHA256SUMS

  - name: Install PVE server dependencies
    pip:
      name: proxmoxer

  - name: Get next VMID
    ansible.builtin.shell: |
      pvesh get /cluster/nextid
    register: next_vmid

  - name: Set VMID
    set_fact:
      vmid: "{{ next_vmid.stdout }}"

  - name: Create new VM
    ansible.builtin.shell: |
      qm create {{ vmid }} --name {{ proxmox_template_name }} --memory 8096 --net0 virtio,bridge=vmbr0

  - name: Convert cloud image to disk
    ansible.builtin.shell: |
      qm importdisk {{ vmid }} /mnt/pve/{{ raid_name }}/template/iso/ubuntu-20.04-minimal-cloudimg-amd64.img {{ raid_name }}

  - name: Assign to to SCSi drive on VM
    ansible.builtin.shell: |
      qm set {{ vmid }} --scsihw virtio-scsi-pci --scsi0 {{ raid_name }}:{{ vmid }}/vm-{{ vmid }}-disk-0.raw

  - name: Create Cloud-init drive
    ansible.builtin.shell: |
      qm set {{ vmid }} --ide2 {{ raid_name }}:cloudinit

  - name: Set boot priority
    ansible.builtin.shell: |
      qm set {{ vmid }} --boot c --bootdisk scsi0

  - name: Set VGA output
    ansible.builtin.shell: |
      qm set {{ vmid }} --serial0 socket --vga serial0

  - name: Set Cloud-init config file
    ansible.builtin.copy:
      dest: /mnt/pve/{{ raid_name }}/snippets/user-config.yml
      content: |
        #cloud-config
        hostname: ubuntu2004
        manage_etc_hosts: true
        user: ubuntu
        password: ubuntu
        chpasswd:
          expire: False
        users:
          - default
        package_upgrade: true
        packages:
          - qemu-guest-agent
        runcmd:
          - sudo sed -i "/^[^#]*PasswordAuthentication.*/c\PasswordAuthentication yes" /etc/ssh/sshd_config
          - sudo rm /etc/machine-id
          - sudo rm /var/lib/dbus/machine-id
          - sudo truncate -s 0 /etc/machine-id
          - sudo ln -s /etc/machine-id /var/lib/dbus/machine-id
          - mkdir -p /home/ubuntu/.ssh
          - shutdown

  - name: Assign to to SCSi drive on VM
    ansible.builtin.shell: |
      qm set {{ vmid }} --ipconfig0 ip=dhcp

  - name: Enable QEMU Guest Agent
    ansible.builtin.shell: |
      qm set {{ vmid }} --agent 1

  - name: Assign to to SCSi drive on VM
    ansible.builtin.shell: |
      qm set {{ vmid }} --cicustom "user={{ raid_name }}:snippets/user-config.yml"

  - name: Start VM
    ansible.builtin.shell: |
      qm start {{ vmid }}

  - name: Wait for VM setup to complete
    ansible.builtin.shell: |
      qm status {{ vmid }}
    register: vm_status
    retries: 25
    delay: 10
    until: '"stopped" in vm_status.stdout'

  - name: Convert VM to template
    ansible.builtin.shell: |
      qm template {{ vmid }}
