---

all:
  hosts:
    proxmox:
      ansible_host: 10.0.128.128
      ansible_port: 22

  children:
    physical:
      hosts:
        proxmox:

    k8s-cluster:
      children:
        kube-master:
        kube-node:
