- hosts: k8s-cluster
  become_method: sudo
  become_user: root
  remote_user: vagrant
  become: yes
  gather_facts: no
  serial: "25%"

  tasks:
  - name: apt updates
    apt:
        force_apt_get: yes
        update_cache: yes
        upgrade: safe
        autoremove: yes
        autoclean: yes

  - name: Checking if updates require reboot
    stat:
      path: /var/run/reboot-required
    register: reboot_required

  - name: Reboot
    reboot:
      reboot_timeout: 3600
    when: reboot_required.stat.exists
