- hosts: physical
  become_method: sudo
  become_user: root
  become: true

  vars:
    raid_name: raid

  tasks:
  - name: Download Ubuntu cloud image
    get_url:
      url: https://releases.ubuntu.com/20.04/ubuntu-20.04.3-live-server-amd64.iso
      dest: /mnt/pve/{{ raid_name }}/template/iso/ubuntu-20.04.3-live-server-amd64.iso

  - name: Install PVE server dependencies
    pip:
      name: proxmoxer

  - name: Get next VMID
    shell: |
      pvesh get /cluster/nextid
    register: next_vmid
  
  - name: Set VMID
    set_fact:
      vmid: "{{ next_vmid.stdout }}"

  - name: Create new VM
    shell: |
      qm create {{ vmid }} --memory 8096 --net0 virtio,bridge=vmbr0

  - name: Convert cloud image to disk
    shell: |
      qm importdisk {{ vmid }} /mnt/pve/{{ raid_name }}/template/iso/ubuntu-20.04-minimal-cloudimg-amd64.img {{ raid_name }}

  - name: Assign to to SCSi drive on VM
    shell: |
      qm set {{ vmid }} --scsihw virtio-scsi-pci --scsi0 {{ raid_name }}:{{ vmid }}/vm-{{ vmid }}-disk-0.raw

  - name: Create Cloud-init drive
    shell: |
      qm set {{ vmid }} --ide2 {{ raid_name }}:cloudinit

  - name: Set boot priority
    shell: |
      qm set {{ vmid }} --boot c --bootdisk scsi0

  - name: Set VGA output
    shell: |
      qm set {{ vmid }} --serial0 socket --vga serial0

  - name: Set Cloud-init config file
    ansible.builtin.copy:
      dest: /mnt/pve/{{ raid_name }}/snippets/user-config.yml
      content: |
        #cloud-config
        hostname: ubuntu2004server
        manage_etc_hosts: true
        user: ubuntu
        password: ubuntu
        chpasswd:
          expire: False
        users:
          - default
        package_upgrade: true
        packages:
          - qemu-guest-agent

  - name: Set Cloud-init network config file
    ansible.builtin.copy:
      dest: /mnt/pve/{{ raid_name }}/snippets/network-config.yml
      content: |
        #cloud-config
        version: 1
        config:
            - type: physical
              name: eth0
              subnets:
              - type: dhcp4
            - type: nameserver
              address:
              - '1.1.1.1'
              - '8.8.8.8'
              search:
              - 'localdomain'

  - name: Assign to to SCSi drive on VM
    shell: |
      qm set {{ vmid }} --ipconfig0 ip=dhcp

  - name: Assign to to SCSi drive on VM
    shell: |
      qm set {{ vmid }} --cicustom "user={{ raid_name }}:snippets/user-config.yml"

  - name: Start VM
    community.general.proxmox_kvm:
      api_user: "{{ proxmox_details.api_user }}"
      api_password: "{{ proxmox_details.api_password }}"
      api_host: "{{ proxmox_details.host_ip }}"
      node: "{{ proxmox_details.node }}"
      vmid: "{{ vmid }}"
      state: started
