- hosts: proxmox
  become_method: sudo
  become_user: root
  become: yes

  tasks:
    - name: Ensure enterprise repo file is not present
      file:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        state: absent

    - name: Get pveversion for backup file
      shell: "pveversion | awk -F / '{print $2}'"
      register: pveversion
      check_mode: no

    - name: backup up original file
      copy:
        remote_src: True
        src: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
        dest: "/usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js.bak-{{ pveversion.stdout }}"
        force: no

    - name: modify line which performs license check
      replace:
        path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
        regexp: "data.status \\!== \\'Active\\'"
        replace: "false"
      notify: restart pveproxy

  handlers:
    - name: restart pveproxy
      service:
        name: pveproxy
        state: restarted
