- hosts: physical
  become_method: sudo
  become_user: root
  become: true

  vars:
    raid_name: raid

  tasks:
  - name: Download Ubuntu cloud image
    get_url:
      url: https://cloud-images.ubuntu.com/minimal/releases/focal/release/ubuntu-20.04-minimal-cloudimg-amd64.img
      dest: /mnt/pve/{{ raid_name }}/template/iso/ubuntu-20.04-minimal-cloudimg-amd64.img

  - name: Install PVE server dependencies
    pip:
      name: proxmoxer

  - name: Create new VM using cloud-init with a username and password
    community.general.proxmox_kvm:
      node: "{{ proxmox_details.node }}"
      api_user: "{{ proxmox_details.api_user }}"
      api_password: "{{ proxmox_details.api_password }}"
      api_host: "{{ proxmox_details.host_ip }}"
      name: afsddfas
      boot: c
      bootdisk: scsi0
      ide:
        ide2: 'local:cloudinit,format=qcow2'
      ciuser: mylinuxuser
      cipassword: supersecret
      searchdomains: 'mydomain.internal'
      nameservers: 1.1.1.1
      net:
        net0: 'virtio,bridge=vmbr0,tag=77'
      ipconfig:
        ipconfig0: 'ip=192.168.1.1/24,gw=192.168.1.1'
    register: new_vm

  - name: Get new VM's id
    set_fact:
      vmid: "{{ new_vm.vmid }}"

  - name: Import the new disk
    ansible.builtin.shell: qm importdisk {{ vmid }} /mnt/pve/{{ raid_name }}/template/iso/ubuntu-20.04-minimal-cloudimg-amd64.img {{ raid_name }} -format qcow2

  - name: Mount the new disk
    ansible.builtin.shell: qm set {{ vmid }} --scsihw virtio-scsi-pci --scsi0 /mnt/pve/raid/images/{{ vmid }}/vm-{{ vmid }}-disk-0.qcow2

  - name: Expand the new disk
    ansible.builtin.shell: qm resize {{ vmid }} scsi0 +30G
