- hosts: localhost

  tasks:
    - name: Start VM
      community.general.proxmox_kvm:
        api_user: "{{ proxmox_details.api_user }}"
        api_password: "{{ proxmox_details.api_password }}"
        api_host: "{{ proxmox_details.host_ip }}"
        node: "{{ proxmox_details.node }}"
        vmid: "{{ hostvars[item].proxmox_vmid }}"
        state: started
      when: hostvars[item].proxmox_vmid is defined
      with_items: "{{ groups['all'] }}"
      ignore_errors: True
